<?php

namespace AppUserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Find the users that should be notified about a journal going dark.
     * 
     * @return User[]
     */
    public function findUserToNotify() {
        return $this->findBy(array(
            'notify' => true,
            'enabled' => true,
        ));
    }
}
