<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuContainerRepository extends EntityRepository
{
    public function getOpenContainer() {
        return $this->findOneBy(
            array('open' => true), 
            array('id' => 'ASC')
        );
    }
}
