<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Func;

/**
 * DepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends EntityRepository {

	public function search($q) {
		$qb = $this->createQueryBuilder('b');
		$qb->where(
			$qb->expr()->like(
				new Func(
					'CONCAT',
					array(
						'b.uuid',
						'b.comment',
					)
				),
				"'%$q%'"
			)
		);
		$query = $qb->getQuery();
		$listed = $query->getResult();
		return $listed;
	}

}
