<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Func;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends EntityRepository {

    /**
     * Search for a journal.
     *
     * @param string $q
     * @return Journal[]
     */
    public function search($q) {
        $qb = $this->createQueryBuilder('j');
        $qb->where(
                $qb->expr()->like(
                        new Func(
                                'CONCAT', 
                                array('j.title', 'j.issn', 'j.url', 'j.email', 'j.publisherName')),
                        "'%$q%'"
                )
        );
        $query = $qb->getQuery();
        $journals = $query->getResult();
        return $journals;
    }

    /**
     * Find journals by status.
     *
     * @param string $status
     * @return Journal[]
     */
    public function findByStatus($status) {
        return $this->findBy(array(
            'status' => $status,
        ));
    }
}
