<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermOfUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseHistoryRepository extends EntityRepository
{
    /**
     * @param \AppBundle\Entity\TermOfUse $term
     * @return TermOfUse[]
     */
    public function getTermHistory($termId) {
        return $this->findBy(array(
            'termId' => $termId,
        ));
    }
}
