<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermOfUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseRepository extends EntityRepository
{
    public function getTerms() {
        $qb = $this->createQueryBuilder('t')
                ->orderBy('t.weight', 'ASC')
                ->getQuery();
        return $qb->getResult();
    }
}
