<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermOfUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermOfUseHistoryRepository extends EntityRepository
{
    /**
     * Get the complete history for a term.
     * 
     * @param int $termId
     * @return TermOfUseHistory[]
     */
    public function getTermHistory($termId) {
        return $this->findBy(array(
            'termId' => $termId,
        ));
    }

    /**
     * @todo add a function to list the term ids with a count of history entries.
     */
}
